Add hidden retreat and invitation
FJNR-inc/Blitz-API pull request #140
Opened 2019-08-14 09:13 UTC by Jerome-Celle

| Q                                          | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                     | [Fix, Features, Documentation, Enhancement]
| Tickets (_issues_) concerned               | []

---

##### What have you changed ?
...

##### How did you change it ?
...

##### Is there a special consideration?
...

Verification :
 -  [ ] My branch name respect the standard defined in `CONTRIBUTING.md`
 -  [ ] All my commits respect the standard defined in `CONTRIBUTING.md`
 -  [ ] My additions are I18N
 -  [ ] This Pull-Request fully meets the requirements defined in the issue
 -  [ ] I added or modified the attached tests
 -  [ ] I added or modified the documentation

2019-08-14 15:31 UTC, RignonNoel requested changes
Attention a la gestion des reservation cancelled et au safeDelete, bien s'assurer de prendre ces cas particuliers en compte.

Très bon travail sinon!

2019-08-14 15:31 UTC, RignonNoel commented on .env.example
> +#RETREAT_INVITATION_URL=https://example.com/retreat_invitation/{{token}}
Please update the `CHANGELOG` so we don't forgot to update the ENV variable of the production system

2019-08-14 15:31 UTC, RignonNoel commented on blitz_api/settings.py
> +            config('FORGOT_PASSWORD_URL',
Not the good ENV variable used at this line

2019-08-14 15:31 UTC, RignonNoel commented on retirement/models.py
> +        on_delete=models.SET_NULL,
Did you test how it works with the `safeDelete` functionnality ?

2019-08-14 15:31 UTC, RignonNoel commented on retirement/models.py
> +        primary_key=True)
Pour des questions de performances on conseil tres souvent de garder l'ID comme primaryKey, on peut cependant utiliser l'attribut uniqu pour rendre le token uniqu sur toutes les lignes aussi.

2019-08-14 15:31 UTC, RignonNoel commented on retirement/models.py
> +        return self.retreat_reservations.count()
Attention aux reservations cancelled, je pense qu'il faut faire quelque chose de plus complexe que juste un `count()`

2019-08-14 15:31 UTC, RignonNoel commented on retirement/tests/tests_viewset_Reservation.py
> +        self.maxDiff = 10000
Cette ligne est utilisé pour débugger, il ne faut cependant pas les commits pour eviter des problemes de logs trop lourd sur les outils de CI

2019-08-26 08:26 UTC, Jerome-Celle commented on retirement/tests/tests_viewset_Reservation.py
> +        self.maxDiff = 10000
Hum, j'suis pas tant d'accord parce que si un CI sort une erreur, bah vaut mieux avoir son contenu non?
Et ensuite, on à se problème à beaucoup d'endroits, c'est une conséquence de tester de gros dictionnaires d'un coup. Du coup ptete à voir pour retravailler notre façon de tester le retour d'un serializer?

2019-09-01 13:48 UTC, RignonNoel requested changes

2019-09-01 13:48 UTC, RignonNoel commented on store/models.py
> +        max_length=1000,
As you can see on this documentation, `max_length` is not enforced on database level. It's just for front-end generation purpose when we don't use DRF on top of it.

https://docs.djangoproject.com/en/2.2/ref/models/fields/#textfield

2019-09-01 15:48 UTC, RignonNoel approved these changes

2019-09-01 15:58 UTC, merged