add lang field in user model
FJNR-inc/Blitz-API pull request #208
Opened 2019-10-02 16:44 UTC by willkoua

| Q                                          | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                     | [Enhancement]
| Tickets (_issues_) concerned               | [TV-250]

---

##### What have you changed ?
add lang field in user model

##### How did you change it ?
...

##### Is there a special consideration?
...

Verification :
 -  [ ] My branch name respect the standard defined in `CONTRIBUTING.md`
 -  [ ] All my commits respect the standard defined in `CONTRIBUTING.md`
 -  [ ] My additions are I18N
 -  [ ] This Pull-Request fully meets the requirements defined in the issue
 -  [ ] I added or modified the attached tests
 -  [ ] I added or modified the documentation

2019-10-03 09:58 UTC, RignonNoel requested changes
You did not change the tests to verifyif we can change this field on register and edit profile

2019-10-03 09:58 UTC, RignonNoel commented on blitz_api/models.py
> +    LANG_CHOICE = (
LANG_CHOICE**S**

2019-10-03 09:58 UTC, RignonNoel commented on blitz_api/models.py
> +    lang = models.CharField(
Should be "Language" to be clear

2019-10-03 17:11 UTC, willkoua commented on blitz_api/models.py
> +    LANG_CHOICE = (
done

2019-10-03 17:11 UTC, willkoua commented on blitz_api/models.py
> +    lang = models.CharField(
done

2019-10-09 13:27 UTC, RignonNoel requested changes

2019-10-10 08:25 UTC, RignonNoel requested changes
Aussi, tu avais dit que tu ferais une seule migration quand Jerome t'a demande

2019-10-10 08:25 UTC, RignonNoel commented on blitz_api/models.py
> +        verbose_name=_("Lang"),
Lang -> Language

2019-10-10 12:00 UTC, Clara-Celle requested changes

2019-10-10 12:00 UTC, Jerome-Celle commented on blitz_api/migrations/0022_auto_20191003_1254.py
> +    ]
Penses à merger les deux migrations en une

2019-10-10 15:27 UTC, RignonNoel approved these changes

2019-10-10 15:27 UTC, merged